language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.8.1"

install:
  - pip install $DJANGO
  - pip install pillow
  - pip install django-ckeditor

script:
  - python manage.py test